add the fink_mm pipeline into raw2science
astrolabsoftware/fink-broker pull request #811
Opened 2024-02-09 16:18 UTC by FusRoman

**IMPORTANT: Please create an issue first before opening a Pull Request.**
Linked to issue(s):
- Closes #810 

## What changes were proposed in this pull request?
Modification inside raw2science will now launch the streaming cross-match with the GCN.

Modification of the exit_after behaviour: The script will wait until gcn arrives in the stream. When GCN comes, the script returns to the exit_after original behaviour and will wait for the remaining time. If no GCN arrives until the end of the streams, this one will end normally. 

Add a science2mm.py in fink_broker containing the call to fink_mm ztf_join_gcn function

## How was this patch tested?
CI

2024-02-28 09:51 UTC, JulienPeloton reviewed
Thanks @FusRoman for the great PR :-) I left some comments. Also, I am not a super fan of f-string -- could you replace them by `"{}".format` instead? I think it increases the readability.

2024-02-28 09:51 UTC, JulienPeloton commented on bin/distribute.py
> +        config = get_config({"--config": args.mmconfigpath})
The launch of the MM module should be conditional. If the user does not provide the config, then this part should be skipped (and only the other filters will be activated).

2024-02-28 09:51 UTC, JulienPeloton commented on bin/fink_test
> +export NIGHT_INT=20231018
I do not understand the need for both?

2024-02-28 09:51 UTC, JulienPeloton commented on bin/raw2science.py
> +        config = get_config({"--config": args.mmconfigpath})
Again, the activation of this module should be conditional. If the config is not given this should be skipped.

2024-02-28 15:31 UTC, FusRoman commented on bin/fink_test
> +export NIGHT_INT=20231018
Me neither; it was because you put both previously, so I kept the original types to prevent possible bugs. If it is not useful, I can keep only one.

https://github.com/astrolabsoftware/fink-broker/blob/490f2b3d0197f88853bcda05261cde5a1341e127/bin/fink_test#L102

https://github.com/astrolabsoftware/fink-broker/blob/490f2b3d0197f88853bcda05261cde5a1341e127/bin/fink_test#L114

2024-05-22 12:17 UTC, JulienPeloton requested changes

2024-05-22 12:17 UTC, JulienPeloton commented on conf/fink.conf.dev
> +ONLINE_DATA_PREFIX=${FINK_HOME}/online_test
`online_integration`

2024-05-23 05:50 UTC, JulienPeloton commented on bin/fink_test
> +export NIGHT_INT=20231018
I merged the two declarations.

2024-05-23 06:18 UTC, JulienPeloton commented on conf/fink.conf.dev
> +# Path to fink-mm configuration file
Specify that putting `no-config` disable fink-mm operations

2024-05-23 15:47 UTC, JulienPeloton commented on bin/raw2science.py
> +                countquery_mm = science2mm(args, config, gcndatapath, scitmpdatapath)
```
Traceback (most recent call last):
  File "/home/julien.peloton/fink-broker/bin/raw2science.py", line 241, in <module>
    main()
  File "/home/julien.peloton/fink-broker/bin/raw2science.py", line 185, in main
    time_spent_in_wait, countquery_mm = launch_fink_mm(args, scitmpdatapath)
  File "/home/julien.peloton/fink-broker/bin/raw2science.py", line 90, in launch_fink_mm
    countquery_mm = science2mm(args, config, gcndatapath, scitmpdatapath)
  File "/home/julien.peloton/fink-broker/dist/fink_broker-3.1-py3.9.egg/fink_broker/mm_utils.py", line 87, in science2mm
  File "/opt/anaconda/lib/python3.9/site-packages/fink_mm/ztf_join_gcn.py", line 478, in ztf_join_gcn_stream
    gcn_rawevent.join(
  File "/opt/spark-3/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 3935, in dropDuplicates
  File "/opt/spark-3/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/opt/spark-3/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 175, in deco
pyspark.errors.exceptions.captured.AnalysisException: Cannot resolve column name "gcn_status" among (raw_event, observatory, instrument, event, ivorn,        triggerId, gcn_ra, gcn_dec, err_arcmin, ackTime, triggerTimejd, triggerTimeUTC, hpix_circle, hpix, objectId, candidate, prv_candidates,                       brokerIngestTimestamp, brokerStartProcessTimestamp, fink_broker_version, fink_science_version, cdsxmatch, DR3Name, Plx, e_Plx, vsx, spicy_id, spicy_class,    gcvs, x3hsp, x4lac, mangrove, roid, rf_snia_vs_nonia, snn_snia_vs_nonia, snn_sn_vs_all, mulens, nalerthist, rf_kn_vs_nonkn, t2, anomaly_score, lc_features_g, lc_features_r, jd_first_real_det, jdstarthist_dt, mag_rate, sigma_rate, lower_rate, upper_rate, delta_time, from_upper, brokerEndProcessTimestamp, hpix,      ztf_ra, ztf_dec).
```

2024-05-23 18:43 UTC, JulienPeloton commented on bin/raw2science.py
> +                countquery_mm = science2mm(args, config, gcndatapath, scitmpdatapath)
```
[julien.peloton@vm-75222 ~]$ fink_mm --version
0.20.1
```

2024-06-11 05:14 UTC, merged