Calculating anomaly_score and sending notifications for user models
astrolabsoftware/fink-broker pull request #929
Opened 2024-12-13 10:26 UTC by Knispel2

2024-12-20 08:19 UTC, JulienPeloton requested changes
Thanks @Knispel2  -- could you fix PEP8 complains?

2024-12-20 08:19 UTC, JulienPeloton commented on fink_broker/science.py
> +    ANOMALY_MODELS = [''] + ANOMALY_MODELS # '' - model for a public channel
In Python, global scope variable cannot not be used for assignment inside a local scope.

```python
# global definition
a = 1

def f():
  a = a +1
  return a
print(f())
```

will lead to 

```
UnboundLocalError: local variable 'a' referenced before assignment
```

So you need to define a new variable name for the expanded list of models.

2024-12-20 16:04 UTC, Knispel2 commented on fink_broker/science.py
> +    ANOMALY_MODELS = [''] + ANOMALY_MODELS # '' - model for a public channel
Sorry, silly mistake, I overlooked it

2024-12-22 22:20 UTC, Knispel2 commented
Sorry, using ruff is unusual for me

2024-12-22 22:22 UTC, JulienPeloton commented
No worries -- just installing `ruff==0.8.4` and running:

```bash
ruff check --preview fink_broker/*.py
ruff format --check --preview fink_broker/*.py
ruff check --preview bin/*.py
ruff format --preview bin/*.py
```

Should lint the code correctly (see https://github.com/astrolabsoftware/fink-broker/blob/master/.github/workflows/linter.yml)

2024-12-22 22:29 UTC, Knispel2 commented
> ```shell
> ruff format --preview bin/*.py
> ```
I get this:

![image](https://github.com/user-attachments/assets/06c9db17-9071-4930-86e1-73474a89cdff)

2024-12-22 22:33 UTC, JulienPeloton commented
All good now :-)

2024-12-22 22:34 UTC, Knispel2 commented
Thanks, `ruff format --preview` helped

2024-12-23 06:56 UTC, merged